# Generated by Django 4.0.1 on 2022-01-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_users', '0003_customuser_is_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verify_token',
            field=models.TextField(default=''),
        ),
    ]
