# Generated by Django 4.0.1 on 2022-01-29 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_users', '0004_customuser_verify_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_verify',
        ),
    ]
