# Generated by Django 4.0.1 on 2022-01-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_users', '0005_remove_customuser_is_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='verify_token',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verify',
            field=models.BooleanField(default=False, verbose_name='verify'),
        ),
    ]
