# Generated by Django 4.0.1 on 2022-01-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='main_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
